# Generated by Django 5.2.7 on 2025-11-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_notas/')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos_notas/')),
            ],
        ),
    ]
